name: CI/CD
on: [push]

jobs:
  Build:
    name: Build

    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev'
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 22
        uses: actions/setup-node@v3
        with:
          node-version: "22"

      - name: Install dependencies
        working-directory: ./front
        run: npm install

      - name: Build project
        working-directory: ./front
        run: npm run build

  Deploy-Production:
    name: Deploy to Vercel (Production)
    needs: Build

    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3

      - name: use Node.js 22
        uses: actions/setup-node@v3
        with:
          node-version: "22"

      - name: Install vercel Cli
        run: npm install --global vercel@latest

      - name: Pull Vercel Enviromental Variables
        working-directory: ./front
        run: vercel pull --yes --token=${{ secrets.VERCEL_TOKEN_ID }}

      - name: Trigger Vercel Deployment
        working-directory: ./front
        run: vercel deploy --no-wait --token=${{ secrets.VERCEL_TOKEN_ID }}
