name: Next.js CI/CD
env:
  VERCEL_TOKEN_ID: ${{ secrets.VERCEL_TOKEN }}
  VERCEL_USER_ID: ${{ secrets.VERCEL_USER_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  push:
    branches:
      - main # déclenche sur chaque push dans main
  pull_request: # déclenche aussi sur les PR

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Récupérer le code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Installer Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      # 3. Installer les dépendances
      - name: Install dependencies
        run: npm install

      # 4. Vérifier que l'app build bien
      - name: Build Next.js app
        run: npm run build

  deploy:
    runs-on: ubuntu-latest
    needs: build # attendre que le build avant de déployer
    if: github.ref == 'refs/heads/main' # déploiement seulement sur main

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Build Next.js app
        run: npm run build

      # 6. Déploiement sur Vercel
      - name: Deploy to Vercel
        run: npx vercel --prod --token=$VERCEL_TOKEN --scope $VERCEL_USER_ID --confirm --project $VERCEL_PROJECT_ID
